---
title: " The Class Clown, the Drama Queen and the Nerd: How Movie Genres are mirroring our favorite High School Stereotypes "
author: "Anna Ballou, Nicole Lawler, Jessica Jacinto"
date: "59/2019"
output: 
  html_document:
    theme: journal
    fig_width: 6
    fig_height: 4
    fig_caption: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rmarkdown::paged_table
```

```{r, message = FALSE}
library(tidyverse)
library(RMySQL)
library(ggplot2)
library(rmarkdown)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "imdb")
knitr::opts_chunk$set(connection = db, max.print = 400)
```

```{r, message = FALSE, warning = FALSE}
db <- dbConnect(MySQL(),
                host = "scidb.smith.edu",
                user = "mth292",
                password = "RememberPi",
                dbname = "imdb")
```
                
```{r, message = FALSE, warning = FALSE}
sql1 <- "
SELECT 
	FLOOR(t.production_year/10) *  10 AS decade,
	mi.info AS genre, 
	COUNT(DISTINCT mi.id) AS number_of_films
    
FROM movie_info AS mi
INNER JOIN title AS t ON t.id = mi.movie_id
WHERE mi.info_type_id = 3
AND t.production_year >= 1920
AND t.production_year < 2010
AND mi.info <> 'Short'
AND mi.info <> 'Erotica'
AND mi.info <> 'Experimental'
AND mi.info <> 'Lifestyle'
AND mi.info <> 'Sport'
AND mi.info <> 'Talk-Show'
AND mi.info <> 'News'
GROUP BY floor(t.production_year/10) *  10, mi.info
ORDER BY 1,2
;"

db1 <- db %>%
  dbGetQuery(sql1)

paged_table(db1)
```

```{r, message = FALSE, warning = FALSE}
plot1 <- ggplot(data = db1, aes(x = decade, y = number_of_films)) +
  geom_line() +
  facet_wrap(~genre) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
print(plot1)
```


```{r, message = FALSE, warning = FALSE}
sql2 <- "
SELECT 
	FLOOR(t.production_year/10) *  10 AS decade,
	COALESCE(mi.info,'Other') AS genre, 
    SUM(CONVERT(
			TRIM(
				REPLACE(
					REPLACE(
						SUBSTRING_INDEX(mi2.info,'(USA)',1) -- split on 'USA'
						 ,'$','') -- close replace dollar sign with space
                           , ',', '') -- close replace comma with space 
                           ) -- close trim
                           , signed) -- close convert
						) AS Funding -- close sum
FROM title AS t
INNER JOIN movie_info AS mi ON t.id = mi.movie_id
INNER JOIN movie_info AS mi2 ON mi.movie_id = mi2.movie_id
WHERE mi.info_type_id = 3
AND mi2.info_type_id = 107
AND SUBSTRING(mi2.info,1,1) = '$'
AND mi2.info LIKE '%(USA)%'
AND t.production_year >= 1920
AND t.production_year <= 2010
GROUP BY FLOOR(t.production_year/10) *  10, mi.info
ORDER BY 1,2
;"

db2 <- db %>%
  dbGetQuery(sql2)

paged_table(db2)
```

```{r, message = FALSE, warning = FALSE}
plot2 <- ggplot(data = db2, aes(x = decade, y = Funding)) +
  geom_line() +
  facet_wrap(~genre) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
print(plot2)
```


